// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCcTfS9LYJ2kttrCCrDeCR0CrwqWYinfA',
    appId: '1:884248627658:web:ec383f292d13486f26e733',
    messagingSenderId: '884248627658',
    projectId: 'vibe-together-app-fa1a4',
    authDomain: 'vibe-together-app-fa1a4.firebaseapp.com',
    storageBucket: 'vibe-together-app-fa1a4.firebasestorage.app',
    measurementId: 'G-NPNMCVTPZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi7dj2lrK5m1aqx5ADJlhw1kbOZlky0TU',
    appId: '1:884248627658:android:8a91d3313a2c48be26e733',
    messagingSenderId: '884248627658',
    projectId: 'vibe-together-app-fa1a4',
    storageBucket: 'vibe-together-app-fa1a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxJZ43QBQf5spDHn_63TcBFFefgw-syjo',
    appId: '1:884248627658:ios:308d722de676dd2c26e733',
    messagingSenderId: '884248627658',
    projectId: 'vibe-together-app-fa1a4',
    storageBucket: 'vibe-together-app-fa1a4.firebasestorage.app',
    iosClientId: '884248627658-0uh1dbl54lirirpcgjsl55jp4ip30hc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibeTogetherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxJZ43QBQf5spDHn_63TcBFFefgw-syjo',
    appId: '1:884248627658:ios:308d722de676dd2c26e733',
    messagingSenderId: '884248627658',
    projectId: 'vibe-together-app-fa1a4',
    storageBucket: 'vibe-together-app-fa1a4.firebasestorage.app',
    iosClientId: '884248627658-0uh1dbl54lirirpcgjsl55jp4ip30hc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibeTogetherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCcTfS9LYJ2kttrCCrDeCR0CrwqWYinfA',
    appId: '1:884248627658:web:8d33033123e4d98926e733',
    messagingSenderId: '884248627658',
    projectId: 'vibe-together-app-fa1a4',
    authDomain: 'vibe-together-app-fa1a4.firebaseapp.com',
    storageBucket: 'vibe-together-app-fa1a4.firebasestorage.app',
    measurementId: 'G-NTJYJ17HBK',
  );
}
